### ISSUE TITLE
When I use UIViewController instead of UINavigationController scan doesn't work

### ISSUE THREAD

**Issue by shapkar** [izhoubin/QRScanner#1]
I don't have UINavigationController in my app and instead of navigationController.push(qr) I am using present(qr) and then scan doesn't work.

Any help?

Thank you!

**Comment by shapkar** [comment]
I found the issue..

Probably "AVCaptureInputPortFormatDescriptionDidChange" behaves differently when a ViewController is pushed to navigationController and when is presented.

When a ViewController is presented, QRScannerView frame is (0, 0, 0, 0) in viewDidLoad and it changes on viewDidLayoutSubviews so I posted a notification there:
`nc.post(name: Notification.Name("viewDidLayoutSubviews"), object: nil)`

and then in setupCameraSession(), changed the observer name from "AVCaptureInputPortFormatDescriptionDidChange" to "viewDidLayoutSubviews":

`
nc.addObserver(forName: NSNotification.Name("viewDidLayoutSubviews"), object: nil, queue: nil, using: {[weak self] (noti) in
      guard let sf = self else{
           return
      } metaOutput.rectOfInterest = sf.previewLayer!.metadataOutputRectConverted(fromLayerRect: sf.squareView.frame)
 })
`

nc variable is defined at the top of the class QRScannerViewController
`let nc = NotificationCenter.default`

**Comment by izhoubin** [comment]
This issue 

> I found the issue..
> 
> Probably "AVCaptureInputPortFormatDescriptionDidChange" behaves differently when a ViewController is pushed to navigationController and when is presented.
> 
> When a ViewController is presented, QRScannerView frame is (0, 0, 0, 0) in viewDidLoad and it changes on viewDidLayoutSubviews so I posted a notification there:
> `nc.post(name: Notification.Name("viewDidLayoutSubviews"), object: nil)`
> 
> and then in setupCameraSession(), changed the observer name from "AVCaptureInputPortFormatDescriptionDidChange" to "viewDidLayoutSubviews":
> 
> `nc.addObserver(forName: NSNotification.Name("viewDidLayoutSubviews"), object: nil, queue: nil, using: {[weak self] (noti) in guard let sf = self else{ return } metaOutput.rectOfInterest = sf.previewLayer!.metadataOutputRectConverted(fromLayerRect: sf.squareView.frame) })`
> 
> nc variable is defined at the top of the class QRScannerViewController
> `let nc = NotificationCenter.default`

Just like your comment, the observer get `AVCaptureInputPortFormatDescriptionDidChange` notification before 
method `viewDidLayoutSubviews` called.
So i add
```Swift
view.setNeedsLayout()
view.layoutIfNeeded()
```
in `setUpLayers()`,and a present demo is available now.

Thank you for your feedback，the version of `0.0.9` may fix this issue .
